version: "2"

services:
  db:
    image: deadrobots/pixi:datastore
    container_name: pixidb
    ports:
      - "27017:27017"
      - "28017:28017"
    expose:
      - "27017"
      - "28017"

  app:
    build: ./app
    ports:
      - "8000:8000"
      - "8090:8090"
